version: '3.5'

services:
    # PHP fpm
    application-backend:
        image: application-backend:latest
        restart: always
        tty: true
        working_dir: /var/www/application
        env_file:
            - .env
        volumes:
            - .:/var/www/application
        container_name: application-backend

    # MySQL Service
    application-mysql:
        image: library/mysql:8.0
        container_name: application-mysql
        restart: always
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: app_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: 111111
            MYSQL_ROOT_PASSWORD: admin
            SERVICE_NAME: mysql
        volumes:
            - applicationMysqlData:/var/lib/mysql
            - applicationMysqlFiles:/var/lib/mysql-files


#Docker Volumes
volumes:
    applicationMysqlData:
        driver: local
    applicationMysqlFiles:
        driver: local
